default:
  "data_folder": "./data"
  "country_borders_path": "./countries/ne_50m_admin_0_countries.shp"
  "reviewed_plant_checklist": "./data/plant_checklist_reviewed.xlsx"
  "bee_sp_codes_file": "./data/bee-sps.csv"